# Generated by Django 4.0.5 on 2022-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penolong', '0002_jenis_hewan_jenis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hewan',
            name='gambar',
            field=models.ImageField(null=True, upload_to='gambar'),
        ),
    ]
